name: Setting up backened and OIDC

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::872515279375:role/OIDC-Role_Faisal
          aws-region: us-east-1
          role-session-name: Github-Actions-Terraform

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Verify Terraform backend
        run: |
          echo "Checking if backend state exists in S3..."
          aws s3 ls s3://YOUR_BUCKET_NAME/YOUR_KEY_PATH/terraform.tfstate || {
            echo "❌ Backend state file not found in S3!"
            exit 1
          }
          echo "✅ Backend state file found in S3"


      - name: Terraform Plan
        run: terraform plan -no-color -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan